### ISSUE TITLE
Abysmal performance

### ISSUE THREAD

**Issue by TobleMiner** [ffnord/mesh-announce#29]
This package has severe performance issues:
1. All providers are recompiled for each and every request
2. Many providers spawn external processes on each request
3. There is no way to cache results inside providers

Those three issues combined result in an average runtime of 120 (!) ms for each ```nodeinfo``` query in Freifunk Kiel.

The first problem can be solved quite easily by precompiling the snippets of all providers.

The last two problems however will probably require rewriting the provider handing to treat what's currently just a "code snippet" as a python module so that it can preserve state over multiple runs (or even have some kind of init method).

**Comment by rubo77** [comment]
How much time does the first step already save?

**Comment by TobleMiner** [comment]
Only around 10 percent. The biggest problems are invocations of ```lsb_release``` and ```fastd```.

**Comment by jplitza** [comment]
Thanks for these oberservations! A cache definitely would be a good thing, probably similar to what respondd does on the nodes: Cache the whole result of a category for some time.

Regarding the code snippet style: I came up with this design because of extremely simple providers like statistics.loadavg, as a complete module would have meant a 500% overhead. Then, it was fun fitting in more complicated providers like nodeinfo.network.addresses. But the functional style became a bit unreadable due to the functional character. So I'm open to see a different approach.

**Comment by TobleMiner** [comment]
It's not quite the 21st of February anymore but I did eventually find some time to add a cache to mesh-announce: #30

**Comment by rubo77** [comment]
This issue can be closed then? Or is there something more to do her?
