### ISSUE TITLE
Gluon v2020.2 emits primary_domainy_code

### ISSUE THREAD

**Issue by mweinelt** [ffnord/mesh-announce#61]
See https://github.com/freifunk-gluon/gluon/pull/2027/files#diff-6174b1a86ab3714de32ec046179b4ecbR133.

For gateways it is probably more feasible to emit a `primary_domain_code` instead of a `domain_code`, since they don't really belong to any pretty domain name, but to the primary physical domain.

This is a step to fix up the relationship between pretty multidomain names and the underlying physical domain, that is currently not decernible from e.g. meshviewer.

**Comment by AiyionPrime** [comment]
I think `primary_domain_code` should become a provided option, but not instead of a `domain_code`.
Considering a community, that got its stuff well enough together, to even have supernodes on-site of a domain.
Same scenario applies if some organisation in a community wants to run dedicated supernodes for testing, or just their own guests.
I think emitting both would be sensible, which would furthermore not introduce breaking changes.
